# azure-pipelines.yml
pool: { vmImage: ubuntu-latest }
strategy:
  matrix:
    foo:
      VAR: foo
    bar:
      VAR: bar

stages:
  jobs:
  - job: Bar
    steps:
    - template: template_bar.yml
      parameters:
        MESSAGE: conditional job on variable from matrix
    condition: eq(VAR, 'bar')
  - job: Foo
    steps:
    - bash: echo foo
      displayName: alternative
    condition: eq(VAR, 'foo')
