# azure-pipelines.yml
pool: { vmImage: ubuntu-latest }
strategy:
  matrix:
    foo:
      VAR: foo
    bar:
      VAR: bar
steps:
- bash: echo $(VAR)
  displayName: value from main file
- template: template.yml
  parameters:
    VAL_AS_MACRO: $(VAR)
    VAL_AS_VARIABLE_DOT: variables.VAR
- ${{if eq(VAR, 'bar')}}:
  - template: template_bar.yml
    displayName: template conditional on variable from matrix
- ${{if eq(variables.VAR, 'bar')}}:
  - template: template_bar.yml
    displayName: template conditional on variable from matrix with "variables." syntax
# this next one would fail to compile
# - template: template_bar.yml
#   condition: eq(VAR, 'bar')
#   displayName: condition conditional on variable from matrix
# this next one would fail to compile
# - template: template_bar.yml
#   condition: eq(variables.VAR, 'bar')
#   displayName: condition conditional on variable from matrix with "variables." syntax

